### ISSUE TITLE
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted. in New 2.0

### ISSUE THREAD

**Issue by Filyx20** [zacimac/SimpleMusic#11]
Sooooo i just now cloned the repo and it's not wanting to start at all. Up above is my terminal output.

Only edits i did in the config file is set my bot token and set whitelist to false.

```
bots@DellBianServ:~/SimpleMusic$ node -v
v16.8.0
bots@DellBianServ:~/SimpleMusic$ npm -v
7.21.1
bots@DellBianServ:~/SimpleMusic$ npm i

up to date, audited 475 packages in 1s

92 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
bots@DellBianServ:~/SimpleMusic$ npm start

> simplemusic@2.0.0 start
> cd src && node index.js

/home/bots/SimpleMusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244
        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/bots/SimpleMusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
    at async Client.login (/home/bots/SimpleMusic/node_modules/discord.js/src/client/Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}
bots@DellBianServ:~/SimpleMusic$
```

**Comment by zacwm** [comment]
I had a feature idea I was trying to implement during development that required some privileged intents that are turned on in the Discord developer portal. I scrapped this idea before merging.
Just had to double check, but the bot does not require the members intent

Creating a new commit to fix this issue now.
